export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const USERS_LOADED = 'USERS_LOADED';
export const USERS_ERROR = 'USERS_ERROR';
export const USERS_CLEAR = 'USERS_CLEAR';

export const CINEMA_LOADED = 'CINEMA_LOADED';
export const CINEMA_ERROR = 'CINEMA_ERROR';
export const CINEMA_CLEAR = 'CINEMA_CLEAR';

export const TICKETS_LOADED = 'TICKETS_LOADED';
export const TICKETS_CLEAR = 'TICKETS_CLEAR';
export const TICKETS_ERROR = 'TICKETS_ERROR';

export const TRANSACTION_LOADED = 'TRANSACTION_LOADED';
export const TRANSACTION_CLEAR = 'TRANSACTION_CLEAR';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';

export const REFERRAL_EARNING_LOADED = 'REFERRAL_EARNING_LOADED';
export const REFERRAL_EARNING_CLEAR = 'REFERRAL_EARNING_CLEAR';
export const REFERRAL_EARNING_ERROR = 'REFERRAL_EARNING_ERROR';

export const REFERRAL_CONTACTS_LOADED = 'REFERRAL_CONTACTS_LOADED';
export const REFERRAL_CONTACTS_CLEAR = 'REFERRAL_CONTACTS_CLEAR';
export const REFERRAL_CONTACTS_ERROR = 'REFERRAL_CONTACTS_ERROR';

export const ALL_TICKETS_LOADED = 'ALL_TICKETS_LOADED';
export const ALL_TICKETS_CLEAR = 'ALL_TICKETS_CLEAR';
export const ALL_TICKETS_ERROR = 'ALL_TICKETS_ERROR';